export const FETCH_CTDONHANG = 'FETCH_CTDONHANG';
export const FETCH_SUCCESS_CTDONHANG = 'FETCH_SUCCESS_CTDONHANG';
export const FETCH_FAIDLED_CTDONHANG = 'FETCH_FAIDLED_CTDONHANG';

export const FILTER_CTDONHANG = 'FILTER_CTDONHANG';
export const FILTER_CTDONHANG_SUCCESS = 'FILTER_CTDONHANG_SUCCESS';

export const THEM_CTDONHANG = 'THEM_CTDONHANG';
export const THEM_CTDONHANG_SUCCESS = 'THEM_CTDONHANG_SUCCESS';
export const THEM_CTDONHANG_FAILED = 'THEM_CTDONHANG_FAILED';

export const SET_CTDONHANG_EDITTING = 'SET_CTDONHANG_EDITTING';
export const SET_CTDONHANG_EDITTING_NULL = 'SET_CTDONHANG_EDITTING_NULL';

export const UPDATE_CTDONHANG = 'UPDATE_CTDONHANG';
export const UPDATE_CTDONHANG_SUCCESS = 'UPDATE_CTDONHANG_SUCCESS';
export const UPDATE_CTDONHANG_FAILED = 'UPDATE_CTDONHANG_FAILED';

export const DELETE_CTDONHANG = 'DELETE_CTDONHANG';
export const DELETE_CTDONHANG_SUCCESS = 'DELETE_CTDONHANG_SUCCESS';
export const DELETE_CTDONHANG_FAILED = 'DELETE_CTDONHANG_FAILED';