export const FETCH_CT_KHUYENMAI = 'FETCH_CT_KHUYENMAI';
export const FETCH_SUCCESS_CT_KHUYENMAI = 'FETCH_SUCCESS_CT_KHUYENMAI';
export const FETCH_FAIDLED_CT_KHUYENMAI = 'FETCH_FAIDLED_CT_KHUYENMAI';

export const FILTER_CT_KHUYENMAI = 'FILTER_CT_KHUYENMAI';
export const FILTER_CT_KHUYENMAI_SUCCESS = 'FILTER_CT_KHUYENMAI_SUCCESS';

export const THEM_CT_KHUYENMAI = 'THEM_CT_KHUYENMAI';
export const THEM_CT_KHUYENMAI_SUCCESS = 'THEM_CT_KHUYENMAI_SUCCESS';
export const THEM_CT_KHUYENMAI_FAILED = 'THEM_CT_KHUYENMAI_FAILED';

export const SET_CT_KHUYENMAI_EDITTING = 'SET_CT_KHUYENMAI_EDITTING';
export const SET_CT_KHUYENMAI_EDITTING_NULL = 'SET_CT_KHUYENMAI_EDITTING_NULL';

export const UPDATE_CT_KHUYENMAI = 'UPDATE_CT_KHUYENMAI';
export const UPDATE_CT_KHUYENMAI_SUCCESS = 'UPDATE_CT_KHUYENMAI_SUCCESS';
export const UPDATE_CT_KHUYENMAI_FAILED = 'UPDATE_CT_KHUYENMAI_FAILED';

export const DELETE_CT_KHUYENMAI = 'DELETE_CT_KHUYENMAI';
export const DELETE_CT_KHUYENMAI_SUCCESS = 'DELETE_CT_KHUYENMAI_SUCCESS';
export const DELETE_CT_KHUYENMAI_FAILED = 'DELETE_KHUYENMAI_FAILED';