export const FETCH_DATHANG = 'FETCH_DATHANG';
export const FETCH_SUCCESS_DATHANG = 'FETCH_SUCCESS_DATHANG';
export const FETCH_FAIDLED_DATHANG = 'FETCH_FAIDLED_DATHANG';

export const FILTER_DATHANG = 'FILTER_DATHANG';
export const FILTER_DATHANG_SUCCESS = 'FILTER_DATHANG_SUCCESS';

export const THEM_DATHANG = 'THEM_DATHANG';
export const THEM_DATHANG_SUCCESS = 'THEM_DATHANG_SUCCESS';
export const THEM_DATHANG_FAILED = 'THEM_DATHANG_FAILED';

export const SET_DATHANG_EDITTING = 'SET_DATHANG_EDITTING';
export const SET_DATHANG_EDITTING_NULL = 'SET_DATHANG_EDITTING_NULL';

export const UPDATE_DATHANG = 'UPDATE_DATHANG';
export const UPDATE_DATHANG_SUCCESS = 'UPDATE_DATHANG_SUCCESS';
export const UPDATE_DATHANG_FAILED = 'UPDATE_DATHANG_FAILED';

export const DELETE_DATHANG = 'DELETE_DATHANG';
export const DELETE_DATHANG_SUCCESS = 'DELETE_DATHANG_SUCCESS';
export const DELETE_DATHANG_FAILED = 'DELETE_DATHANG_FAILED';