export const FETCH_GIAY = 'FETCH_GIAY';
export const FETCH_NEWPRODUCT = 'FETCH_NEWPRODUCT';
export const FETCH_SUCCESS_GIAY = 'FETCH_SUCCESS_GIAY';
export const FETCH_FAIDLED_GIAY = 'FETCH_FAIDLED_GIAY';

export const FILTER_GIAY = 'FILTER_GIAY';
export const FILTER_GIAY_SUCCESS = 'FILTER_GIAY_SUCCESS';

export const THEM_GIAY = 'THEM_GIAY';
export const THEM_GIAY_SUCCESS = 'THEM_GIAY_SUCCESS';
export const THEM_GIAY_FAILED = 'THEM_GIAY_FAILED';

export const SET_GIAY_EDITTING = 'SET_GIAY_EDITTING';
export const SET_GIAY_EDITTING_NULL = 'SET_GIAY_EDITTING_NULL';

export const UPDATE_GIAY = 'UPDATE_GIAY';
export const UPDATE_GIAY_SUCCESS = 'UPDATE_GIAY_SUCCESS';
export const UPDATE_GIAY_FAILED = 'UPDATE_GIAY_FAILED';

export const DELETE_GIAY = 'DELETE_GIAY';
export const DELETE_GIAY_SUCCESS = 'DELETE_GIAY_SUCCESS';
export const DELETE_GIAY_FAILED = 'DELETE_GIAY_FAILED';

export const FETCH_CHITIETMAUSAC = 'FETCH_CHITIETMAUSAC';
export const FETCH_SUCCESS_CHITIETMAUSAC = 'FETCH_SUCCESS_CHITIETMAUSAC';
export const FETCH_FAIDLED_CHITIETMAUSAC = 'FETCH_FAIDLED_CHITIETMAUSAC';

export const FILTER_CHITIETMAUSAC = 'FILTER_CHITIETMAUSAC';
export const FILTER_CHITIETMAUSAC_SUCCESS = 'FILTER_CHITIETMAUSAC_SUCCESS';

export const THEM_CHITIETMAUSAC = 'THEM_CHITIETMAUSAC';
export const THEM_CHITIETMAUSAC_SUCCESS = 'THEM_CHITIETMAUSAC_SUCCESS';
export const THEM_CHITIETMAUSAC_FAILED = 'THEM_CHITIETMAUSAC_FAILED';

export const SET_CHITIETMAUSAC_EDITTING = 'SET_CHITIETMAUSAC_EDITTING';

export const UPDATE_CHITIETMAUSAC = 'UPDATE_CHITIETMAUSAC';
export const UPDATE_CHITIETMAUSAC_SUCCESS = 'UPDATE_CHITIETMAUSAC_SUCCESS';
export const UPDATE_CHITIETMAUSAC_FAILED = 'UPDATE_CHITIETMAUSAC_FAILED';

export const DELETE_CHITIETMAUSAC = 'DELETE_CHITIETMAUSAC';
export const DELETE_CHITIETMAUSAC_SUCCESS = 'DELETE_CHITIETMAUSAC_SUCCESS';
export const DELETE_CHITIETMAUSAC_FAILED = 'DELETE_CHITIETMAUSAC_FAILED';

export const FETCH_CHITIETSIZE = 'FETCH_CHITIETSIZE';
export const FETCH_SUCCESS_CHITIETSIZE = 'FETCH_SUCCESS_CHITIETSIZE';
export const FETCH_FAIDLED_CHITIETSIZE = 'FETCH_FAIDLED_CHITIETSIZE';

export const FILTER_CHITIETSIZE = 'FILTER_CHITIETSIZE';
export const FILTER_CHITIETSIZE_SUCCESS = 'FILTER_CHITIETSIZE_SUCCESS';

export const THEM_CHITIETSIZE = 'THEM_CHITIETSIZE';
export const THEM_CHITIETSIZE_SUCCESS = 'THEM_CHITIETSIZE_SUCCESS';
export const THEM_CHITIETSIZE_FAILED = 'THEM_CHITIETSIZE_FAILED';

export const SET_CHITIETSIZE_EDITTING = 'SET_CHITIETSIZE_EDITTING';

export const UPDATE_CHITIETSIZE = 'UPDATE_CHITIETSIZE';
export const UPDATE_CHITIETSIZE_SUCCESS = 'UPDATE_CHITIETSIZE_SUCCESS';
export const UPDATE_CHITIETSIZE_FAILED = 'UPDATE_CHITIETSIZE_FAILED';

export const DELETE_CHITIETSIZE = 'DELETE_CHITIETSIZE';
export const DELETE_CHITIETSIZE_SUCCESS = 'DELETE_CHITIETSIZE_SUCCESS';
export const DELETE_CHITIETSIZE_FAILED = 'DELETE_CHITIETSIZE_FAILED';

export const SET_DATA_LG = 'SET_DATA_LG';