export const FETCH_KHACHHANG = 'FETCH_KHACHHANG';
export const FETCH_SUCCESS_KHACHHANG = 'FETCH_SUCCESS_KHACHHANG';
export const FETCH_FAIDLED_KHACHHANG = 'FETCH_FAIDLED_KHACHHANG';

export const FILTER_KHACHHANG = 'FILTER_KHACHHANG';
export const FILTER_KHACHHANG_SUCCESS = 'FILTER_KHACHHANG_SUCCESS';

export const THEM_KHACHHANG = 'THEM_KHACHHANG';
export const THEM_KHACHHANG_SUCCESS = 'THEM_KHACHHANG_SUCCESS';
export const THEM_KHACHHANG_FAILED = 'THEM_KHACHHANG_FAILED';

export const SET_KHACHHANG_EDITTING = 'SET_KHACHHANG_EDITTING';
export const SET_KHACHHANG_EDITTING_NULL = 'SET_KHACHHANG_EDITTING_NULL';

export const UPDATE_KHACHHANG = 'UPDATE_KHACHHANG';
export const UPDATE_KHACHHANG_SUCCESS = 'UPDATE_KHACHHANG_SUCCESS';
export const UPDATE_KHACHHANG_FAILED = 'UPDATE_KHACHHANG_FAILED';

export const DELETE_KHACHHANG = 'DELETE_KHACHHANG';
export const DELETE_KHACHHANG_SUCCESS = 'DELETE_KHACHHANG_SUCCESS';
export const DELETE_KHACHHANG_FAILED = 'DELETE_KHACHHANG_FAILED';