export const FETCH_KHUYENMAI = 'FETCH_KHUYENMAI';
export const FETCH_SUCCESS_KHUYENMAI = 'FETCH_SUCCESS_KHUYENMAI';
export const FETCH_FAIDLED_KHUYENMAI = 'FETCH_FAIDLED_KHUYENMAI';

export const FILTER_KHUYENMAI = 'FILTER_KHUYENMAI';
export const FILTER_KHUYENMAI_SUCCESS = 'FILTER_KHUYENMAI_SUCCESS';

export const THEM_KHUYENMAI = 'THEM_KHUYENMAI';
export const THEM_KHUYENMAI_SUCCESS = 'THEM_KHUYENMAI_SUCCESS';
export const THEM_KHUYENMAI_FAILED = 'THEM_KHUYENMAI_FAILED';

export const SET_KHUYENMAI_EDITTING = 'SET_KHUYENMAI_EDITTING';
export const SET_KHUYENMAI_EDITTING_NULL = 'SET_KHUYENMAI_EDITTING_NULL';

export const UPDATE_KHUYENMAI = 'UPDATE_KHUYENMAI';
export const UPDATE_KHUYENMAI_SUCCESS = 'UPDATE_KHUYENMAI_SUCCESS';
export const UPDATE_KHUYENMAI_FAILED = 'UPDATE_KHUYENMAI_FAILED';

export const DELETE_KHUYENMAI = 'DELETE_KHUYENMAI';
export const DELETE_KHUYENMAI_SUCCESS = 'DELETE_KHUYENMAI_SUCCESS';
export const DELETE_KHUYENMAI_FAILED = 'DELETE_KHUYENMAI_FAILED';