export const FETCH_LOAIGIAY = 'FETCH_LOAIGIAY';
export const FETCH_SUCCESS_LOAIGIAY = 'FETCH_SUCCESS_LOAIGIAY';
export const FETCH_FAIDLED_LOAIGIAY = 'FETCH_FAIDLED_LOAIGIAY';

export const FILTER_LOAIGIAY = 'FILTER_LOAIGIAY';
export const SET_LOAIGIAY = 'SET_LOAIGIAY';

export const THEM_LOAI_GIAY = 'THEM_LOAI_GIAY';
export const THEM_LOAI_GIAY_SUCCESS = 'THEM_LOAI_GIAY_SUCCESS';
export const THEM_LOAI_GIAY_FAILED = 'THEM_LOAI_GIAY_FAILED';

export const SET_LOAIGIAY_EDITTING = 'SET_LOAIGIAY_EDITTING';
export const SET_LOAIGIAY_EDITTING_NULL = 'SET_LOAIGIAY_EDITTING_NULL';

export const UPDATE_LOAIGIAY = 'UPDATE_LOAIGIAY';
export const UPDATE_LOAIGIAY_SUCCESS = 'UPDATE_LOAIGIAY_SUCCESS';
export const UPDATE_LOAIGIAY_FAILED = 'UPDATE_LOAIGIAY_FAILED';

export const DELETE_LOAIGIAY = 'DELETE_LOAIGIAY';
export const DELETE_LOAIGIAY_SUCCESS = 'DELETE_LOAIGIAY_SUCCESS';
export const DELETE_LOAIGIAY_FAILED = 'DELETE_LOAIGIAY_FAILED';