export const FETCH_MAUSAC = 'FETCH_MAUSAC';
export const FETCH_SUCCESS_MAUSAC = 'FETCH_SUCCESS_MAUSAC';
export const FETCH_FAIDLED_MAUSAC = 'FETCH_FAIDLED_MAUSAC';

export const FILTER_MAUSAC = 'FILTER_MAUSAC';
export const SET_MAUSAC = 'SET_MAUSAC';

export const THEM_MAUSAC = 'THEM_MAUSAC';
export const THEM_MAUSAC_SUCCESS = 'THEM_MAUSAC_SUCCESS';
export const THEM_MAUSAC_FAILED = 'THEM_MAUSAC_FAILED';

export const SET_MAUSAC_EDITTING = 'SET_MAUSAC_EDITTING';
export const SET_MAUSAC_EDITTING_NULL = 'SET_MAUSAC_EDITTING_NULL';

export const UPDATE_MAUSAC = 'UPDATE_MAUSAC';
export const UPDATE_MAUSAC_SUCCESS = 'UPDATE_MAUSAC_SUCCESS';
export const UPDATE_MAUSAC_FAILED = 'UPDATE_MAUSAC_FAILED';

export const DELETE_MAUSAC = 'DELETE_MAUSAC';
export const DELETE_MAUSAC_SUCCESS = 'DELETE_MAUSAC_SUCCESS';
export const DELETE_MAUSAC_FAILED = 'DELETE_MAUSAC_FAILED';

export const UPDATE_CHECK = 'UPDATE_CHECK';