export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const CHANGE_MODAL_CONTENT = 'CHANGE_MODAL_CONTENT';
export const CHANGE_MODAL_TITLE = 'CHANGE_MODAL_TITLE';

export const SHOW_MODAL_GIAY = 'SHOW_MODAL_GIAY';
export const HIDE_MODAL_GIAY = 'HIDE_MODAL_GIAY';
export const CHANGE_MODAL_GIAY_CONTENT = 'CHANGE_MODAL_GIAY_CONTENT';
export const CHANGE_MODAL_GIAY_TITLE = 'CHANGE_MODAL_GIAY_TITLE';

export const GET_TOKEN = 'GET_TOKEN';
export const SETTER_TOKEN = 'SETTER_TOKEN';