export const FETCH_SIZE = 'FETCH_SIZE';
export const FETCH_SUCCESS_SIZE = 'FETCH_SUCCESS_SIZE';
export const FETCH_FAIDLED_SIZE = 'FETCH_FAIDLED_SIZE';

export const FILTER_SIZE = 'FILTER_SIZE';
export const GET_SIZE = 'GET_SIZE';

export const THEM_SIZE = 'THEM_SIZE';
export const THEM_SIZE_SUCCESS = 'THEM_SIZE_SUCCESS';
export const THEM_SIZE_FAILED = 'THEM_SIZE_FAILED';

export const SET_SIZE_EDITTING = 'SET_SIZE_EDITTING';
export const SET_SIZE_EDITTING_NULL = 'SET_SIZE_EDITTING_NULL';

export const UPDATE_SIZE = 'UPDATE_SIZE';
export const UPDATE_SIZE_SUCCESS = 'UPDATE_SIZE_SUCCESS';
export const UPDATE_SIZE_FAILED = 'UPDATE_SIZE_FAILED';

export const DELETE_SIZE = 'DELETE_SIZE';
export const DELETE_SIZE_SUCCESS = 'DELETE_SIZE_SUCCESS';
export const DELETE_SIZE_FAILED = 'DELETE_SIZE_FAILED';